#!/usr/bin/env bash

# nitrogen --restore &
xfsettingsd &
xfce4-power-manager &

exec picom &

if [[ $(xrandr -q | grep 'DP2 connected') ]]; then
    xrandr --output eDP1 --primary --mode 2560x1440 --rotate normal --output DP2 --mode 1920x1080 --rotate normal --above eDP1
fi

if [[ ! `pidof xfce-polkit` ]]; then
    /usr/lib/xfce-polkit/xfce-polkit &
fi

exec xrdb -merge ~/.Xresources &

# exec dunst &
# exec plank &
exec thunar --daemon &

ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

exec clamd &
exec touchegg &
exec copyq &
exec kdeconnect-indicator &
exec blueman-applet &

if [[ ! `pidof DiscordCanary` ]]; then
    exec discord-canary --start-minimized &
fi
