#!/usr/bin/env bash

xfsettingsd &
xfce4-power-manager &

exec picom &

# if [[ $(xrandr -q | grep 'DP2 connected') ]]; then
#     xrandr --output eDP1 --primary --mode 2560x1440 --rotate normal --output DP2 --mode 1920x1080 --rotate normal --above eDP1
# fi

if [[ ! `pidof xfce-polkit` ]]; then
    /usr/lib/xfce-polkit/xfce-polkit &
fi

exec xrdb -merge ~/.Xresources &

exec thunar --daemon &

ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

exec clamd &
exec touchegg &
exec copyq &
exec kdeconnect-indicator &
exec blueman-applet &
exec remind -fa -m ~/.reminders/reminders.rem &

if [[ ! `ps ax | grep '/usr/bin/python /usr/bin/firewall-applet' | grep -v grep | awk '{print $1}'` ]]; then
    exec firewall-applet &
fi

if [[ ! `pidof DiscordCanary` ]]; then
    exec discord-canary --start-minimized &
fi